language: python

install:
  - pip install tox --use-mirrors
  - .travis/install_pylint

script: tox -e py27

after_script:
  # Run Pylint
  # (for information only, any errors don't affect the Travis result)
  - pylint --use-ignore-patch=y openphoto
  - pylint --use-ignore-patch=y tests

