language: python

install: pip install tox --use-mirrors

env:
  global:
    - secure: "YdVpLPA0Lt+keVlmVsEMlDStPFU822fj+9LIzQtDgDXWHrFU/CgAOItohsUk\nFwUPRM2k836KQYokYjItaSxWyrxhuViHs6z0w6XI1iQlyQmWOW7K4iuSYAtm\npVIDgUjFWJ9IAg8cEPvpuzj9vrCAbH+1Chv3ZjxkOp7FRUQG68I="
    - secure: "Ss5y5nDeWtA8GKJL5rnX87ZjIFbNhFvY/CfRtFUvv6Fi2+iaoNKExYqIusnb\nb6J1XZlROCb4WTRRghYq0KgYLfLdACcRSuPFK5om/ohh459Od9llHpicx2nK\n8sPnKGZWlIgp5GtbtLfw3q9/GfAmLbg8BPbtcOOR2JEGsOvnxDY="
    - secure: "MZMII9A2aSOMyeKqvf5FDI7BPS7jeeGKRfzxu5fWMv+oGwlu2P6ny9wa8/JG\nTSpmZUDUPiKNK2G/TcZM5q15WJ+vnRDs9bP8CKy77i3P8LtdL7qXCDr1e76m\n2xSB9HRXHnU924U/f5JlihfAP+j4SLMSfXmCBxWhmh4PysGDzdk="
    - secure: "eU2AexG2YXfo/b5qVzFj70uFbEU+8K6mUIGNdE1gWTU7ZNmp3XpW9uL9p3Vj\nIybnKjyWbcNjOFUvEXnfLkABH/JjM7gsP7wNyzLtL+VC9enuVO3GgwGye5l4\ncnFbeZyQe3q9tOzU/iqlu6Tip3hkcjMts0Pbn/yQIEbD32rFbOo="
    - secure: "ipN5YKOvKh0TNsu780/xNjWpgoYY6b+UrdcGqQrF2X6z6scPmQYZbdgJQ+X1\nzuJuPK/1x+qLvJJXgFfaCBNTG3tbpjIVBZso0PXlMUj8RbfpbfRkSGJguqtC\nk5VT/NBhvhkp3kYmm6ap0r4t4g5XrKhpjgcCeV+Lb7tc7Y320S8="

script: .travis/run_travis
